<article>
    <h1>Cadastros</h1>
    <p>Novos dados:</p>
    <div id="gerenciar">
        <ul>
            <li><a href="/admin/cadastrar/secao/setores/">Setores</a></li>
            <li><a href="/admin/cadastrar/secao/filiais">Filiais</a></li>            
            <li><a href="/admin/cadastrar/secao/suportes">Suportes</a></li>
            <li><a href="/admin/cadastrar/secao/servicos">Serviços</a></li>
            <li><a href="/admin/cadastrar/secao/funcionarios">Funcionários</a></li>
            <li><a href="/admin/cadastrar/secao/usuarios">Usuários</a></li>
        </ul>
    </div>        
    <p>Editar/Deletar dados:</p>
    <div id="gerenciar">
        <ul>
            <li><a href="/admin/gerenciar/secao/setores/">Setores</a></li>
            <li><a href="/admin/gerenciar/secao/filiais">Filiais</a></li>     
            <li><a href="/admin/gerenciar/secao/suportes">Suportes</a></li>
            <li><a href="/admin/gerenciar/secao/servicos">Serviços</a></li>
            <li><a href="/admin/gerenciar/secao/funcionarios">Funcionários</a></li>
            <li><a href="/admin/gerenciar/secao/usuarios">Usuários</a></li>
        </ul>
    </div>    
</article>
