<article>   
    <table class="myTable" border="1">
        <caption><h3>Listando todas as ordem de serviços</h3></caption>
            <thead>
                <th>Ordem</th>        
                <th>Data de entrega</th>
                <th>Área do suporte</th>
                <th>Setor atendido</th>
                <th>Tipo de Serviço</th>
                <th>Funcionário</th>
                <th>Filial atendida</th>
                <th>Já realizado?</th>           
            </thead>
        <?php foreach ($view_sql as $dados): ?>
            <tr>
                <td><?= $dados['id'] ?></td>              
                <td><?= date('d/m/Y', strtotime($dados['data_suporte'])) ?></td>
                <td><?= $dados['area'] ?></td>
                <td><?= $dados['setor'] ?></td>
                <td><?= $dados['servico'] ?></td>
                <td><?= $dados['nome_func'] ?></td>
                <td><?= $dados['filial'] ?></td>
                <td><?= $dados['baixa_suporte'] ?></td>               
            </tr>
        <?php endforeach; ?>
    </table>   
</article>